backend/db/migrations/20230314051425_alter_posts_add_column_price_suggestion.sql
[backend 장주성] posts 테이블 가격제안가능 칼럼 추가
=> [backend 장주성] modify: posts 테이블 가격제안가능 칼럼 추가

backend/db/migrations/20230314055359_create_admin_post_status.sql, backend/db/migrations/20230314055423_alter_posts_add_column_admin_post_status_id.sql
[backend 장주성] modify: posts 테이블 admin_post_status_id 칼러 추가
=> [backend 장주성] modify: posts 테이블 admin_post_status_id 칼럼 추가

backend/controllers/userController.js, backend/models/userDao.js, backend/routes/index.js, backend/routes/userRouter.js, backend/services/userService.js, backend/utils/validation.js
- 회원가입 기능구현
- 필요정보(이메일,비밀번호,닉네임,폰번호) 미입력시 키에러 발생유도
- 정규식 사용(이메일,비밀번호, 폰번호)
- 중복가입 발생 방지
📌 폼데이터를 활용한 이미지 업로드(profile_image_url) 기능 차후 추가구현 필요
=> 🔥 [backend] [이홍열] signup 기능구현

backend/app.js, backend/controllers/postController.js, backend/db/migrations/20230314084407_alter_posts_add_column_pullup_time.sql, backend/models/postDao.js, backend/package.json, backend/routes/index.js, backend/routes/postRouter.js, backend/services/postServices.js, backend/utils/error.js
[backend 장주성] modify: posts 테이블 끌어올리기용 datetime column 추가
=> [backend 장주성] modify: posts 테이블 끌어올리기용 datetime column 추가

frontend/pumpkinmarket/src/components/Footer/Footer.js
=> [front][이수민][footer 반응형 구현]

backend/db/migrations/20230315023405_drop_table_posts_post_images.sql
[backend 장주성] modify: post_image 테이블 관계 수정- 다대다 to 다대일
=> [backend 장주성] modify: post_image 테이블 관계 수정- 다대다 to 다대일

backend/controllers/userController.js, backend/models/userDao.js, backend/routes/userRouter.js, backend/services/userService.js, backend/utils/validation.js
=> 🔥[backend][이홍열] signin 기능구현(자체 로그인)

backend/middlewares/auth.js, backend/models/userDao.js, backend/routes/userRouter.js, backend/services/userService.js
=> 🔥[ADD][backend][이홍열] signin 토큰 유효성검사 기능 추가

backend/db/migrations/20230316061013_create_community_categories.sql, backend/db/migrations/20230316061017_create_community_posts.sql, backend/db/migrations/20230316061022_create_community_comments.sql, backend/db/migrations/20230316061025_create_community_likes.sql, backend/db/migrations/20230316061239_alter_accuse_table_add_column.sql
[backend 장주성] modify: community_posts 관련 table 추가
=> [backend 장주성] modify: community_posts 관련 table 추가

backend/db/migrations/20230316090814_create_chat_rooms.sql, backend/db/migrations/20230316091017_alter_table_chats_modify_columns.sql
[backend 장주성] modify: create chat_rooms table 및 chats 테이블 수정
=> [backend 장주성] modify: create chat_rooms table 및 chats 테이블 수정

backend/db/migrations/20230317063823_drop_table_post_locations.sql
[backend 장주성] modify: post location 관련 테이블 수정
=> [backend 장주성] modify: post location 관련 테이블 수정

backend/controllers/cmpostcontroller.js, backend/controllers/userController.js, backend/middlewares/auth.js, backend/models/cmpostDao.js, backend/routes/cmpostRouter.js, backend/routes/index.js, backend/routes/userRouter.js, backend/services/cmpostService.js
- 동네정보 게시물 등록 기능
- 동네정보 게시물 수정 기능
- 동네정보 게시물 삭제 기능
=> 🔥[ADD][backend][이홍열] 동네정보 게시물CRUD API 기능구현

backend/controllers/postController.js, backend/models/postDao.js, backend/routes/postRouter.js, backend/services/postServices.js
[backend 장주성] add: likes 기능 추가
=> [backend 장주성] add: likes 기능 추가

backend/models/postDao.js, backend/models/queryBuilder.js
[backend 장주성] modify: querybuilder 수정
=> [backend 장주성] modify: querybuilder 수정

backend/controllers/postController.js, backend/models/postDao.js, backend/routes/postRouter.js, backend/services/postServices.js
[backend 장주성] modify: post minor fix
=> [backend 장주성] modify: post minor fix

backend/db/migrations/20230321044100_delete_column_users_social_types.sql, backend/models/userDao.js
[backend 장주성] modify: users table social_types 수정
=> [backend 장주성] modify: users table social_types 수정

backend/backOffice/routes/index.js, backend/controllers/commentController.js, backend/models/userDao.js, backend/services/postServices.js
[backend 장주성] modify: 불필요한 console.log 제거
=> [backend 장주성] modify: 불필요한 console.log 제거

backend/controllers/postController.js, backend/models/postDao.js, backend/services/postServices.js
[backend 장주성] modify: createPost 인자 받는 방식 변경
=> [backend 장주성] modify: createPost 인자 받는 방식 변경

backend/controllers/cmpostcontroller.js, backend/controllers/commentController.js, backend/models/cmpostDao.js, backend/services/cmpostService.js
- request 에서 받는 정보의 방식 req.body 내용 변경
=> 🔥[MODIFY][backend][이홍열] 동네정보 게시물 작성 API 수정

backend/models/userDao.js
[backend 장주성] modify: userDao 수정
=> [backend 장주성] modify: userDao 수정

backend/controllers/postController.js, backend/models/postDao.js, backend/models/queryBuilder.js, backend/services/postServices.js
[backend 장주성] add: 게시글 제목 & 위치 검색 기능 구현
=> [backend 장주성] add: 게시글 제목 & 위치 검색 기능 구현

backend/backOffice/controllers/cmpostController.js, backend/backOffice/models/cmpostDao.js, backend/backOffice/routes/cmpostRouter.js, backend/backOffice/routes/index.js, backend/backOffice/services/cmpostService.js, backend/controllers/userController.js
- 동네정보 게시물 조회
- 동네정보 게시물 삭제
기능구현
=> 🔥[ADD][backend][이홍열] admin 동네정보 게시물 관리 API

backend/backOffice/models/cmpostDao.js, backend/backOffice/services/cmpostService.js
=> 🔥[MODIFY][backend][이홍열] admin 동네정보 게시물 관리 API

backend/controllers/cmpostcontroller.js, backend/models/cmpostDao.js, backend/routes/cmpostRouter.js, backend/services/cmpostService.js
=> 🔥[ADD][backend][이홍열] 동네정보 게시물 조회 API 기능구현

backend/db/migrations/20230323014008_alter_users_add_columns.sql
[backend 장주성] modify: 와임 api 연동 위한 users 테이블 변경
=> [backend 장주성] modify: 와임 api 연동 위한 users 테이블 변경

frontend/pumpkinmarket/src/pages/Product/Product.js
=> [front] [이수민] 게시글 좋아요 기능 구현

frontend/pumpkinmarket/src/Router.js
=> [front][이수민]MenuProvider 라우터 수정

frontend/pumpkinmarket/src/Router.js
=> [front][이수민]main 라우터 수정

backend/models/cmpostDao.js
=> 🔥[MODIFY][backend][이홍열] 동네정보 게시물 상세페이지 쿼리문 작성

backend/controllers/myPageController.js, backend/models/myPageDao.js, backend/models/userDao.js, backend/routes/index.js, backend/routes/myPageRouter.js, backend/services/myPageService.js
[backend 장주성] add: 마이페이지 조회 기능 추가
=> [backend 장주성] add: 마이페이지 조회 기능 추가

backend/backOffice/models/cmpostDao.js
- 댓글이 있는 게시물 삭제가 안되는 에러발생(DB fk 무결성 원인)
- 트랜잭션 기능으로 댓글 삭제 후 게시물 삭제 가능하도록 수정
=> 🔥[MODIFY][backend][이홍열] admin 동네정보 게시물 삭제기능 수정

frontend/pumpkinmarket/src/Router.js, frontend/pumpkinmarket/src/pages/Product/Product.js, frontend/pumpkinmarket/src/pages/ProductList/ProductList.js
=> [front][이수민]채팅하기 버튼 추가

frontend/pumpkinmarket/src/config/config.js
=> [front][이수민]mypage config 파일 추가

backend/models/postDao.js
[backend 장주성] modify: post delete 시 제약조건 문제 수정
=> [backend 장주성] modify: post delete 시 제약조건 문제 수정

frontend/pumpkinmarket/package-lock.json, frontend/pumpkinmarket/package.json, frontend/pumpkinmarket/src/pages/Login/Login.js, frontend/pumpkinmarket/src/pages/Product/Product.js, frontend/pumpkinmarket/yarn.lock
=> [front][이수민]Feature/product

backend/models/cmpostDao.js
- 리스트페이지, 상세페이지에 title data가 누락되어 추가 반영
=> 🔥[MODIFY][backend][이홍열] 동네정보 게시물 조회 수정(title column 반영)

backend/controllers/cmpostcontroller.js, backend/models/cmpostDao.js, backend/models/commentDao.js, backend/routes/cmpostRouter.js, backend/services/cmpostService.js
- 동네정보 게시물 댓글 삭제 시 exist 확인 기능 수정 추가(result.registed)
=> 🔥[ADD][backend][이홍열] 동네정보 게시물 좋아요 API 기능구현

frontend/pumpkinmarket/src/Router.js, frontend/pumpkinmarket/src/components/Nav/MenuProvider.js, frontend/pumpkinmarket/src/config/config.js, frontend/pumpkinmarket/src/pages/NeighborInfo/Comment.js, frontend/pumpkinmarket/src/pages/NeighborInfo/NeighborInfo.js, frontend/pumpkinmarket/src/pages/Product/Product.js, frontend/pumpkinmarket/tailwind.config.js
=> [front][이수민]동네정보 댓글 조회 데이터 변경

frontend/pumpkinmarket/src/components/Nav/Nav.js
=> [front] [이수민]nav search Img file 경로 수정

frontend/pumpkinmarket/src/pages/Posting/Posting.js
=> [front] [이수민] posting price input 수정

frontend/pumpkinmarket/src/pages/Mypage/DealingsInventory.js, frontend/pumpkinmarket/src/pages/NeighborInfoList/AllNeighborInfo.js, frontend/pumpkinmarket/src/pages/NeighborInfoList/NeighborInfoList.js
=> [front] [이수민] 동네정보 전체 조회

backend/utils/validation.js
- 회원가입 시 비밀번호 특수문자에 ₩, `, # 3가지 문자 추가
=> 🔥[MODIFY][backend][이홍열] 회원가입 비밀번호 정규식 수정

frontend/pumpkinmarket/src/config/config.js, frontend/pumpkinmarket/src/pages/Mypage/ChattingInventory.js, frontend/pumpkinmarket/src/pages/Mypage/DealingsInventory.js, frontend/pumpkinmarket/src/pages/Mypage/Mypage.js, frontend/pumpkinmarket/src/pages/Mypage/UserInfo.js, frontend/pumpkinmarket/src/pages/Mypage/UserInfoUpload.js
=> 마이페이지 회원정보 수정 기능 구현 완료

frontend/pumpkinmarket/src/pages/Mypage/Mypage.js
=> [front][이수민]프로필 이미지 사진 크기 조절

frontend/pumpkinmarket/src/components/Nav/Nav.js
=> [front][이수민]로그아웃 버튼 추가

frontend/pumpkinmarket/src/Router.js, frontend/pumpkinmarket/src/pages/Login/Login.js, frontend/pumpkinmarket/src/pages/Login/Weam.js
=> [front] [이수민]Feature/login

backend/controllers/userController.js, backend/models/userDao.js, backend/services/userService.js
- 와임로그아웃 주석코드 삭제
- user 레이어드 아키텍쳐 불필요한 코드 삭제
=> 🔥[MODIFY][backend][이홍열] 와임로그인 기능 수정

frontend/pumpkinmarket/src/pages/Mypage/ChattingInventory.js, frontend/pumpkinmarket/src/pages/Mypage/CommentInventory.js, frontend/pumpkinmarket/src/pages/Mypage/CommunityInventory.js, frontend/pumpkinmarket/src/pages/Mypage/DealingsInventory.js, frontend/pumpkinmarket/src/pages/Mypage/DeleteModal.js, frontend/pumpkinmarket/src/pages/NeighborInfo/Comment.js
=> [front] [이수민] Modify: 삭제기능 오류 수정

backend/app.js, backend/controllers/cmpostcontroller.js, backend/models/cmpostDao.js, backend/services/cmpostService.js
- 게시물 삭제시 작성한 유저만 삭제할수 있도록 수정
- 게시물 작성 한 유저 외 게시물 삭제 시 에러메시지 발생
- app.js 서버에러 발생 소스코드 불필요로 삭제
=> 🔥[MODIFY][backend][이홍열] 동네정보 게시물 삭제기능 수정

backend/controllers/commentController.js, backend/models/commentDao.js, backend/routes/commentRouter.js, backend/services/commentService.js
- commentRouter에 delete endpoint cmpostId 추가
- commentController에 parameter 추가
- commentService에 에러메시지 추가
- commentDao에 service 기능을 위한 쿼리문 추가
=> 🔥[MODIFY][backend][이홍열] 동네정보 게시물 댓글  삭제기능 수정

backend/middlewares/auth.js
=> 🔥[MODIFY][backend][이홍열] auth.js 오타 수정

frontend/pumpkinmarket/src/config/config.js, frontend/pumpkinmarket/src/pages/AdminProject/CommunityPage.js, frontend/pumpkinmarket/src/pages/AdminProject/CommunityTable.js, frontend/pumpkinmarket/src/pages/AdminProject/DealingsPage.js, frontend/pumpkinmarket/src/pages/AdminProject/MemberPage.js, frontend/pumpkinmarket/src/pages/Chat/Chat.js, frontend/pumpkinmarket/src/pages/Login/Login.js, frontend/pumpkinmarket/src/pages/Login/Waem.js, frontend/pumpkinmarket/src/pages/SignUp/SignUp.js
=> [front][이수민]Modify: 공용 API로 연결
